version: 1.0.0.{build}

branches:
  only:
    - master

before_build:
  - nuget restore

test:
  # assemblies to test - optional
  assemblies:
    - **\Wox.Skype.Test\bin\$(configuration)\Wox.Skype.Test.dll

