version: 1.0.0.{build}

build:
  project: Wox.Skype.sln

cache:
  - packages -> **\packages.config 

branches:
  only:
    - master

init: 
  - regsvr32 Interop.SKYPE4COMLib.dll /s

before_build:
  - nuget restore

test:
  assemblies:
    - '**\Wox.Skype.Test\bin\$(configuration)\Wox.Skype.Test.dll'

artifacts:
  - path: '**\Wox.Skype\Wox.Skype\bin\$(configuration)\Wox.Skype.wox'