version: 1.0.0.{build}

build:
  project: Wox.Skype.sln

cache:
  - packages -> **\packages.config 

branches:
  only:
    - master

before_build:
  - mkdir "Wox.Skype\bin\$(configuration)\"
  - regsvr32 /s Interop.SKYPE4COMLib.dll
  - copy Interop.SKYPE4COMLib.dll "Wox.Skype\bin\$(configuration)\Interop.SKYPE4COMLib.dll" /Y
  - nuget restore

test:
  assemblies:
    - '**\Wox.Skype.Test\bin\$(configuration)\Wox.Skype.Test.dll'

artifacts:
  - path: '**\Wox.Skype\Wox.Skype\bin\$(configuration)\Wox.Skype.wox'

notifications:
  - provider: Slack
    auth_token:
      secure: cNQ4nndjuemYoNBkNMROjh4huxAlgxKTSi4OmbJihVANGcy3PR0gUL9KEeZHYsRM
    channel: activities
    template: "{{message}}, {{commitId}}, ..."