version: 1.0.0.{build}

cache:
  - packages -> **\packages.config 

branches:
  only:
    - master

before_build:
  - regsvr32 "%APPVEYOR_BUILD_FOLDER%\Interop.SKYPE4COMLib.dll"
  - nuget restore

test:
  assemblies:
    - '**\Wox.Skype.Test\bin\$(configuration)\Wox.Skype.Test.dll'

artifacts:
 
  # pushing a single file
  - path: '**\Wox.Skype\Wox.Skype\bin\$(configuration)\Wox.Skype.wox'