version: 1.0.0.{build}

build:
  project: Wox.Skype.sln

init:
  - git config --global core.autocrlf true

skip_commits:
  message: /readme.*/

environment:
  nunitPath: 'packages\NUnit.Runners.2.6.4\tools\nunit-console-x86.exe'
  reportPath: 'packages\ReportGenerator.2.1.4.0\ReportGenerator.exe'
  coverPath: 'packages\coveralls.io.1.3.4\tools\coveralls.net.exe'
  openPath: 'packages\OpenCover.4.5.3723\OpenCover.Console.exe'
  testDir: 'Wox.Skype.Test\bin\Debug'
  testDlls: 'Wox.Skype.Test.dll'
  coverResultFile: '_CodeCoverageResult.xml'
  COVERALLS_REPO_TOKEN:
    secure: nhZlROX6ElGcNP+EWzsmZt6ihx3hgLZmt7aRGoR5YVCbgfkmpbsdLd5xm2vDybsa
  GITHUB_ACCESS_TOKEN:
    secure: pmwS6u8RTwhUxbUQQp/BHKxoy3c6UwZAKcTqgGSmOrw95itjLkVgS/mu5SDM0zrE

cache:
  - packages -> **\packages.config 

branches:
  only:
    - master

before_build:
  - regsvr32 /s Skype4COM.dll
  - nuget restore

test_script:
  - cmd: >-
          "%openPath%" -target:%nunitPath% -targetargs:"%testDlls% /nologo /noshadow" -output:"%coverResultFile%" -register:user -targetdir:"%testDir%" -filter:"+[Wox.Skype*]*" -filter:"-[Wox.Skype*Test]*"

after_test: 
  - cmd: >- 
          "%coverPath%" --opencover %coverResultFile% --full-sources

artifacts:
  - path: '**\Wox.Skype.wox'
    name: 'Wox.Skype.wox' 

deploy:
  release: Wox.Skype-v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: $(GITHUB_ACCESS_TOKEN)
  artifact: Wox.Skype.wox
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true

notifications:
  - provider: Slack
    auth_token:
      secure: cNQ4nndjuemYoNBkNMROjh4huxAlgxKTSi4OmbJihVANGcy3PR0gUL9KEeZHYsRM
    channel: activities

on_success:
  - cmd: >- 
          "%reportPath%" -reports:%coverResultFile% -targetdir:coverage

          git config --global credential.helper store

          git config --global user.email "appveyor@bindsolution.com"

          git config --global user.name "AppVeyor"

  - 7z a coverage.zip coverage/**
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GITHUB_ACCESS_TOKEN):x-oauth-basic@github.com/Ridermansb/wox.skype.git"
  - cmd: >-
          mkdir gh-pages

          cd gh-pages

          git clone -b gh-pages https://github.com/Ridermansb/wox.skype.git .

          cd coverage

          7z e ..\..\coverage.zip  -y

          cd ..
          
          git add .

          git commit -am "Update coverage code report"

  
  - git push origin gh-pages
