version: 1.0.0.{build}

build:
  project: Wox.Skype.sln

cache:
  - packages -> **\packages.config 
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml  

branches:
  only:
    - master

before_build:
  - choco install skype -force -y
  - nuget restore

test:
  assemblies:
    - '**\*Test.dll'

artifacts:
  - path: '**\Wox.Skype.wox'

notifications:
  - provider: Slack
    auth_token:
      secure: cNQ4nndjuemYoNBkNMROjh4huxAlgxKTSi4OmbJihVANGcy3PR0gUL9KEeZHYsRM
    channel: activities
